---
- name: Intro to Ansible Playbooks
  hosts: debian
  

  tasks:
    - name: Add the user 'foo'
      ansible.builtin.user:
         name: foo
         state: present
      become: yes

    - name: upgrade all packages
      apt:
        name: '*'
        state: latest
      become: yes    

    - name: install the latest version of nano
      apt:
        name: nano
        state: latest
      become: yes 

    - name: install the latest version of vim
      apt:
        name: vim
        state: latest
      become: yes  

- name: install Nginx on Debian
  hosts: debian
  become: yes
  
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      

    - name: Create Web Root directory (Debian)
      file:
        path: /var/www/html
        state: directory
      

    - name: Copy index_debian.html to Web Root on Debian
      ansible.builtin.copy:
        src: /home/debian/ansible-intro/index_debian.html
        dest: /var/www/html/index.html
        

    - name: Start Nginx service on Debian
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
        
